# Generated by Django 2.0.5 on 2021-02-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0002_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
